PayDock/mobile-sdk-doc

- setup/index.md
- setup/initialise.md
- setup/integration.md
- widgets/card.md
- widgets/giftcard.md
- widgets/mastercard-src.md
- Updated documentation with removal of pubicKey
- Updated widget contracts using accessToken
- Updated MastercardSRC to ClickToPay
> SDK-575 - [Android] Documentation - Update widget contracts to include Access Token/Remove Public Key

- README.md
- setup/initialise.md
- setup/installation.md
- widgets/card.md
- widgets/giftcard.md
- widgets/mastercard-src.md
- Updated documentation with removal of public key
- Updated widget contracts using access token
> SDK-571 - [iOS] Update initialisation documentation for Access Tokens & widget contracts

- digital-wallet-widgets/afterpay.md
- digital-wallet-widgets/applepay.md
- digital-wallet-widgets/flypay.md
- digital-wallet-widgets/paypal.md
- errors.md
- widgets/card.md
- widgets/giftcard.md
- widgets/mastercard-src.md
- widgets/threeds.md
- Updated error handling documentation for widgets
- Added general API based errors for iOS
- Added inline card details validation errors
> SDK-573 - [iOS] Update error handling documentation to reflect more granular error messages

- digital-wallet-widgets/flypay.md
- Updated Flypay documentation with addition of new clientId field
> SDK-737 - [Documentation] Update FlyPay contract with updated ClientId

- setup/initialise.md
- widgets/threeds.md
- Updated initialisation docs to include test flag (optional param)
> SDK-766 - [Docs] Update MobileSDK contract with enableTestMode field

- digital-wallet-widgets/paypalvault.md
- setup/initialise.md
- Added new page for PayPal Vault (for Android implementation)
> SDK-804  - [Android] Document vault widget operation on github

- errors.md
- Updated Android Generic Exceptions
> SDK-981 - [Docs] Android - Update Generic Exceptions to documentation

- digital-wallet-widgets/paypalvault.md
- Fixed duplication of exceptions for PayPalVault
> SDK-1003 - [Docs - Android] Fix copy/paste on PayPalVault Exceptions 

- digital-wallet-widgets/paypalvault.md
- Removed CreateSessionAuthTokenException from PayPalVault
> SDK-1005 - [Docs - Android] Update PayPalVault Exception, removing CreateSessionAuthTokenException

- digital-wallet-widgets/afterpay.md
- digital-wallet-widgets/flypay.md
- digital-wallet-widgets/paypal.md
- digital-wallet-widgets/paypalvault.md
- widgets/card.md
- widgets/giftcard.md
- Updated android widget contracts with updated params (enabled and loadingDelegate)
- Added callback info for WidgetLoadingDelegate
> SDK-1036 - [Doc Android] Update widget contract documentation

- digital-wallet-widgets/paypalvault.md
- Updated PayPal vault config contract
> SDK-1071 - [Docs - Android] Update PayPal Vault contract

- setup/installation.md
- Updated Android installation documentation to include Jitpack integration
> SDK-1218 - [Android] Document how to use Jitpack to get package

- setup/theming.md
- Updated theming documentation for Android
> SDK-1232 - [Android] Update theme documentation

- fraud/paypaldatacollectorutil.md
- Updated data collector method to `collectDeviceId`
> SDK-1227 - [Android] Update collectDeviceData to function collectDeviceId

- digital-wallet-widgets/paypalvault.md
- Updated PayPalVault exceptions with new exception
> SDK-1269 - [Android] Issue with PayPalVault CancellationException 

- setup/theming.md
- Removed custom SDK theme documentation
- Added new theming documentation referencing Android compose
> SDK-1360 - [Android] Document general theming implementation

- README.md
- digital-wallet-widgets/colespay.md
- Added token handler update for Coles Pay
- Updated ReadMe reference from FlyPay to ColesPay
> SDK-1385 - [Android] Document token contract changes to Coles Pay widget

- README.md
- digital-wallet-widgets/colespay.md
- digital-wallet-widgets/paypal.md
- Added token handler update for PayPal
> SDK-1386 - [Android] Document token contract changes to PayPal widget

- digital-wallet-widgets/afterpay.md
- digital-wallet-widgets/colespay.md
- Added token handler update for Afterpay
> SDK-1387 - [Android] Document token contract changes to AfterPay widget

- widgets/giftcard.md
- Added style appearance docs for GiftCard Widget
> SDK-1373 - [Android] Document gift card customisation changes

- widgets/card.md
> SDK-1372 - [Android] Document card widget customisation changes

- widgets/integrated3ds.md
- Added style appearance docs for Integrated 3DS Widget
> SDK-1518 - [Android] Document Integrated 3ds customisation changes

- widgets/standalone3ds.md
- Added style appearance docs for Standalone 3DS Widget
> SDK-1517 - [Android] Document Standalone 3ds customisation changes

- digital-wallet-widgets/googlepay.md
- Added style appearance docs for Google Pay Widget
> SDK-1376 - [Android] Document Google Pay customisation changes

- digital-wallet-widgets/afterpay.md
- Added style appearance docs for Afterpay Widget
> SDK-1377 - [Android] Document AfterPay customisation changes

- digital-wallet-widgets/googlepay.md
- widgets/address.md
- Updated billing address documentation with additional fields
- Updated Google Pay exceptions with SDK based exception mapping
> SDK-1712 - [Android Documentation] Update Android documentation with latest changes

- digital-wallet-widgets/paypal.md
- Updated PayPal documentation with the use of the SDK
> SDK-1777 - [Android] Update technical documentation for PayPal checkout integration
